services:
  - type: web
    name: my-project
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: public
